name: Pull Request Pipeline

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  review:
    name: Code Review
    uses: ./.github/workflows/review.yaml
    secrets: inherit
    permissions:
      contents: write
      packages: read
      statuses: write
      checks: write

  test:
    name: Test Changelog
    needs: review
    uses: ./.github/workflows/test-changelog.yaml
    secrets: inherit