name: Test Changelog

on:
  workflow_call:

jobs:
  test:
    name: Test Changelog
    runs-on: ubuntu-latest
    
    services:
      mariadb:
        image: mariadb:11.2
        env:
          MARIADB_DATABASE: demo_db
          MARIADB_USER: demo_user
          MARIADB_PASSWORD: demo_password
          MARIADB_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=30s --health-timeout=10s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Wait for MariaDB
      run: |
        until mysqladmin ping -h 127.0.0.1 -P 3306 -u demo_user -pdemo_password --silent; do
          echo 'Waiting for MariaDB...'
          sleep 5
        done

    - name: Run Liquibase tests
      run: |
        docker run \
          -v ${{ github.workspace }}/changelog:/liquibase/changelog \
          -v ${{ github.workspace }}/liquibase-example.properties:/liquibase/liquibase.properties \
          -v ${{ github.workspace }}/scripts:/liquibase/scripts \
          liquibase/liquibase:4.33-alpine /liquibase/scripts/test-update-rollback.sh